### ISSUE TITLE
Error with python 2.7

### ISSUE THREAD

**Issue by helsinq** [tomgross/pycloud#14]
TypeError: str() takes at most 1 argument (2 given)

Traceback (most recent call last):
 (...)
  File "C:\Python27\lib\site-packages\pcloud\api.py", line 48, in __init__
    self.auth_token = self.get_auth_token()
  File "C:\Python27\lib\site-packages\pcloud\api.py", line 73, in get_auth_token
    bytes(sha1(self.username).hexdigest()**, 'utf-8'**) +
TypeError: str() takes at most 1 argument (2 given)

**Comment by tomgross** [comment]
The library does not and will not support Python 2. It is deprecated since a long time.

**Comment by tomgross** [comment]
See setup.py. Python 3.5 is a minimum requirement right now.
